### ISSUE TITLE
There is no `hopp` function displayed in Mathematica.

### ISSUE THREAD

**Issue by hongyi-zhao** [zhangzeyingvv/MagneticTB#3]
The paper [arXiv:2012.08871](https://arxiv.org/abs/2105.09504) says the following:

![image](https://user-images.githubusercontent.com/11155854/155834989-523f5da2-8580-4b26-aec2-4f905d536370.png)

But I can't find any description of it in Mathematica:

![image](https://user-images.githubusercontent.com/11155854/155835026-786722e0-8ae7-46e7-9124-17370d6a9ed2.png)

Regards,
HZ

**Comment by zhangzeyingvv** [comment]
The `hopp` function is in old version of MagneticTB  [(arXiv:2112.10479)](https://arxiv.org/abs/2112.10479), for the latest version [MagneticTB](https://github.com/zhangzeyingvv/MagneticTB), use `hop` rather than `hopp`([Comput. Phys. Commun. 270, 108153 (2022)](https://www.sciencedirect.com/science/article/abs/pii/S0010465521002654)).

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out. BTW, as the title of ([Comput. Phys. Commun. 270, 108153 (2022)](https://www.sciencedirect.com/science/article/abs/pii/S0010465521002654)) indicated: `MagneticTB: A package for tight-binding model of magnetic and non-magnetic materials`, this package is applicable to both magnetic and non-magnetic materials. If so, why do you name it `MagneticTB`?

**Comment by zhangzeyingvv** [comment]
The 230 space groups are subset of  1651 magnetic space groups.

**Comment by hongyi-zhao** [comment]
Got it. Thank you for your explanation.
